### ISSUE TITLE
write some bloody tests

### ISSUE THREAD

**Issue by alsuren** [alsuren/cargo-quickinstall#28]
I've not decided what to test yet, but it's worth adding the infrastructure for testing so that I can add more tests when I need to.

**Comment by progga** [comment]
Thanks David.

I will see if I can come up with an integration test next week.  That may require some refactoring of the existing code in main.rs.  I hope that's okay.

Right now I am not sure how often an integration test should run.  I am thinking perhaps integration tests should only run when the Git *main* branch gets updated rather than every time a pull request is updated.  That way external HTTP requests remain limited.  Let me know if you have any preferences.

**Comment by alsuren** [comment]
We already have a basic smoke test that happens on push to main https://github.com/alsuren/cargo-quickinstall/actions/runs/1883935307/workflow

Potentially we could run this test on pull requests as well?

(It already runs for all of the branches I make, but not for branches made in other people's forks, I think)

Honestly I'm happy to run on every push to every pull request. If you run get-stats.sh then you will see that it looks like someone has integrated it into their CI workflow already. Also, cargo-binstall is using quickinstall packages now, so I'm expecting the stats for this month to be a lot higher than last month. A few extra calls to test our own pull requests won't make much difference.

**Comment by alsuren** [comment]
I forgot to close this when I merged your pr. Sorry about that. Feel free to make other pull requests, to add any tests you would find valuable.
