### ISSUE TITLE
`sccache-dist` is missing for package `sccache`

### ISSUE THREAD

**Issue by NobodyXu** [alsuren/cargo-quickinstall#92]
https://github.com/cargo-bins/cargo-binstall/issues/357

Package `sccache` contains binary `sccache`, but does not contain `sccache-dist`.

**Comment by alsuren** [comment]
Steps to debug:

- [ ] does sccache register sccache-dist in .crates2.json correctly? 
- [ ] are we parsing it correctly? (See around https://github.com/alsuren/cargo-quickinstall/runs/8277920254?check_suite_focus=true#step:4:135 for example logs of us parsing this file)

Once our build process for this package is fixed, we need a way of saying "the package at the default location is broken. Please [give up || try this updated location]". 

- [ ]This probably wants its own ticket, if we don't already have one. I have a possible idea of how we might do this, but am also open to suggestions from binstall people, because you will also be consuming this format.

**Comment by NobodyXu** [comment]
I don't know much about how this works, but sccache-dist requires feature dist-client to be enabled.

While sccache enables all features by default, could it be that quickinstall's CI disables the features somehow?

**Comment by alsuren** [comment]
on my laptop,`cargo install sccache` adds the following to `~/.cargo/.crates2.json`

```json
    "sccache 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)": {
      "version_req": null,
      "bins": [
        "sccache"
      ],
      "features": [],
      "all_features": false,
      "no_default_features": false,
      "profile": "release",
      "target": "aarch64-apple-darwin",
      "rustc": "rustc 1.63.0 (4b91a6ea7 2022-08-08)\nbinary: rustc\ncommit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\ncommit-date: 2022-08-08\nhost: aarch64-apple-darwin\nrelease: 1.63.0\nLLVM version: 14.0.5\n"
    },
```

and does not create an `sccache-dist` binary.

I'm closing this as "works as documented". If you had fallen back all the way to `cargo install sccache` then you would have ended up with the same behavior.

I don't have any plans to support non-default features in `cargo-quickinstall`. If you want non-default features then please wait for cargo-quickbuild. You can track development progress for this on https://github.com/orgs/cargo-quick/projects/1/views/1 or by subscribing to notifications on the cargo-quick repo.
